### ISSUE TITLE
Create and map google group to role error

### ISSUE THREAD

**Issue by mumblez** [grapeshot/google-auth-vault-plugin#1]
Trying to setup the plugin, built and followed up to step 7 on the readme but encountering the errors below, any ideas?

```sh
vault write auth/google/role/devops.team domain="domain.com" email="me@domain.com" policies="hello"

Error writing data to auth/google/role/devops.team: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/google/role/devops.team
Code: 400. Errors:

* bound domain cannot be empty
```

have also tried
`vault write auth/google/role/devops.team@domain.com ...`
but get

```sh
Error writing data to auth/google/role/devops.team@domain.com: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/auth/google/role/devops.team@domain.com
Code: 404. Errors:

* 1 error occurred:

* unsupported path
```

**Comment by tomwilkie** [comment]
> step 7 on the readme but encountering the errors below, any ideas?

It should be `bound_domain` and `bound_email` - the readme is wrong.  I'll update.

**Comment by mumblez** [comment]
thanks, I managed to get past that step, could you possibly clarify what `bounds_email` field is for?

I now get a bug on the next / last step:

```sh
vault read -field=url auth/google/code_url
Error reading auth/google/code_url: Error making API request.

URL: GET http://127.0.0.1:8200/v1/auth/google/code_url
Code: 400. Errors:

* missing config
```

The account is definitely valid as we use the same client creds for other web apps to oauth.

**Comment by tomwilkie** [comment]
> thanks, I managed to get past that step, could you possibly clarify what bounds_email field is for?

`bound_emails` on a role specify what users can authenticate against the role.

> Also, after the step 8, could you add a step for how to login?

The readme has the following steps for logging in:

```
$ open $(vault read -field=url auth/google/code_url)
$ vault write auth/google/login code=$GOOGLE_CODE role=hello
```

The vault write will return a vault token you can use for future operations.

**Comment by mumblez** [comment]
thanks for your help.
